print("Hello Mashhood!")
print("My first Python program on GitHub")
print("My first Python program on GitHub")
print("Hello Mashhood")
print("Welcome to Python")
print("I will become a Cybersecurity Expert")
